[project]
name = "mython"
version = "0.1.0"
description = "Personal python package"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mython = "mython.hello:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
