#! /usr/bin/env python

import argparse
from mython.util import *

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("-t", "--to")
  args = parser.parse_args()

  hello.say_hello(args.to)
  bye.say_bye(args.to)


if __name__ == "__main__":
  main()
