#! /usr/bin/env python3

import argparse

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("-t", "--to")
  args = parser.parse_args()

  say_hello(args.to)


def say_hello(str):
  print("Hello,", str, "!")


if __name__ == "__main__":
  main()
